main:
  - name: 学习
    URL: zh/learn
    weight: 1
    identifier: learn
  - name: 图书
    parent: learn
    URL: zh/learn/books
    weight: 2
  - name: 学习路径
    parent: learn
    URL: zh/learn/learning-path
    weight: 3
  - name: 模式
    parent: learn
    URL: zh/learn/patterns
    weight: 4
  - name: 研究
    parent: learn
    URL: zh/learn/research
    weight: 5
  - name: 活动
    URL: zh/events
    weight: 2
  - name: 社区
    identifier: community
    URL: zh/community
    weight: 3
  - name: 案例故事
    URL: zh/stories
    weight: 4
  - name: 服务目录
    URL: zh/community/services
    parent: community
    weight: 2
  - name: 关于
    identifier: about
    URL: zh/about
    weight: 5
  - name: 公告
    URL: zh/about/announcements
    parent: about
    weight: 1
  - name: 董事会与治理
    URL: zh/about/board
    parent: about
    weight: 2
  - name: 成员
    URL: zh/about/members
    parent: about
    weight: 3
  - name: 赞助
    URL: zh/about/sponsors
    parent: about
    weight: 4
  - name: 行为准则
    URL: zh/about/codeofconduct
    parent: about
    weight: 5
  - name: 联系我们
    URL: zh/about/contact
    parent: about
    weight: 6
footer_left:
  - name: 学习
    URL: zh/learn
    weight: 1
    post: bold
  - name: 图书
    URL: zh/learn/books
    weight: 2
  - name: 学习路径
    URL: zh/learn/learning-path
    weight: 3
  - name: 模式
    URL: zh/learn/patterns
    weight: 4
  - name: 研究
    URL: zh/learn/research
    weight: 5
footer_middle:
  - name: 活动
    URL: zh/events
    weight: 1
    post: bold
  - name: 社区
    URL: zh/community
    weight: 2
    post: bold
    pre: _blank
  - name: 案例故事
    URL: zh/stories
    weight: 3
    post: bold
  - name: 服务目录
    URL: zh/community/services
    weight: 4
  - name: 公告
    URL: zh/about/announcements
    weight: 5
footer_right:
  - name: 关于
    URL: zh/about
    weight: 1
    post: bold
  - name: 董事会与治理
    URL: zh/about/board
    weight: 2
  - name: 成员
    URL: zh/about/members
    weight: 3
  - name: 赞助
    URL: zh/about/sponsors
    weight: 4
  - name: 行为准则
    URL: zh/about/codeofconduct
    weight: 5
  - name: 联系我们
    URL: zh/about/contact
    weight: 6
  - name: 隐私政策
    URL: zh/about/privacy
    weight: 7
